name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  python-exhaustive:
    uses: ./.github/workflows/.nox-session.yml
    with:
      job-name: "python-{0}"
      nox-args: "-t check"
  python-environments:
    uses: ./.github/workflows/.nox-session.yml
    with:
      nox-args: "-s check-tests"
      session-arguments: --no-cov
      runs-on-array: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      python-version-array: '["3.7", "3.8", "3.9", "3.10", "3.11"]'
